# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt
      AppBundle\Entity\AppUser:
        algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      chain_provider:
        chain:
          providers: [db_provider]

      db_provider:
        entity:
          class: AppBundle:AppUser
          property: email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            pattern: ^/

            http_basic: ~

            anonymous: ~

            provider: chain_provider

            form_login:
              login_path: login
              check_path: login

            logout:
              path: /logout

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN}
      - { path: ^/edit/*, roles: IS_AUTHENTICATED_FULLY}
      - { path: ^/delete/*, roles: IS_AUTHENTICATED_FULLY}